### ISSUE TITLE
support defer-but-close-early idiom

### ISSUE THREAD

**Issue by BenLubar** [kisielk/errcheck#105]
``` go
f, err := os.Open("somefile.txt")
if err != nil {
    return nil, err
}
defer f.Close()

// a bunch of processing that either returns a non-nil error or does not return yet

err = f.Close()
if err != nil {
    return nil, err
}

// maybe some more processing that no longer needs the file

return result, nil
```

In this case, checking the error for the deferred call to f.Close would not be needed because the file is either already closed or there is already an error when it runs.

**Comment by shurcooL** [comment]
In that code, you might be closing the same file twice. Is that a valid thing to do?

**Comment by BenLubar** [comment]
In the general case, no, but os.File.Close is idempotent. For any io.Closer that doesn't have side effects on Close calls after the first, this idiom makes closing things and handling errors easier. I don't remember where I first saw it.

**Comment by kisielk** [comment]
I don't think the case is general enough to warrant supporting this in the tool. I think it would be pretty difficult to implement and there would be a lot of troublesome corner cases.

Besides that, the example could be split before the second `f.Close()` to return the intermediate result, and the error could still be checked in the defer.

**Comment by cheapRoc** [comment]
AFAIC this issue should still be addressed in some fashion. [`github.com/jackc/pgx`](http://github.com/jackc/pgx) also has an idempotent function `tx.Rollback()` which is used to roll back a transaction after 15 mins using a `context.Context` timer. From the docs...

```go
// Rollback rolls back the transaction. Rollback will return ErrTxClosed if the
// Tx is already closed, but is otherwise safe to call multiple times. Hence, a
// defer tx.Rollback() is safe even if tx.Commit() will be called first in a
// non-error condition.
```

If the function succeeds than this defer statement returns a specific error which is safe to ignore. Otherwise, there is no error returned.

In this case, I'd like a feature that optionally allows ignoring `defer` errchecks. 

Not sure what, if any, issues there would be around this but I'm perfectly fine with this compromise in my apps given that I handle errs in all other cases using defer. Yes, I could handle the err here as well but this appears to be a widely accepted idiom which even the standard library implements.

**Comment by cheapRoc** [comment]
In my case it looks like I'm able to remove these by using `gometalinter`.

```go
defer r.Close() // nolint: errcheck
```

On second thought, I could see the point of not adding this feature to `errcheck`.

**Comment by dtcaciuc** [comment]
If Close() and Rollback() and such can sometimes return legitimate errors, wouldn't you at least want to know about it? A simple thing to do here would be
```
func closeAndLogError(c io.Closer) {
   if err := c.Close(); err {
      fmt.Errorf("Failed to close")
   }
}

defer closeAndLogError(f)
```
If you really don't care about the error, you can write a similar function that, well, ignores error with `_ := c.Close()`, but then at least you're making it very clear that's your intention.
