### ISSUE TITLE
Special case functions working with `io.Discard`

### ISSUE THREAD

**Issue by simonbos** [kisielk/errcheck#247]
I would like the option of excluding functions / methods working with `io.Discard`. From the [documentation](https://pkg.go.dev/io#Writer):
> Discard is a [Writer](https://pkg.go.dev/io#Writer) on which all Write calls succeed without doing anything.

Currently this is not supported, as you can see in the following example.
```
// main.go
package main

import (
	"bytes"
	"io"
)

func main() {
	b := bytes.NewBuffer([]byte("test"))
	io.Copy(io.Discard, b)
}

// excludes.txt
io.Copy(io.Discard)
```

Then `errcheck -exclude excludes.txt main.go` reports:
```
main.go:10:9:	io.Copy(io.Discard, b)
```

Having `io.Copy(io.Discard)` and maybe some other functions operating on `io.Discard` in the default exclusion list could also make sense.

**Comment by meteorgan** [comment]
add some code here can resolve this problem, but i'm not sure if it's the best solution
https://github.com/kisielk/errcheck/blob/b65821b80eeffbab5e01f8bf1f2cf801e9a284cb/errcheck/errcheck.go#L384

**Comment by dtcaciuc** [comment]
If I understand the problem correctly, then this exclusion would only apply if the sink is a byte buffer, otherwise io.Copy could fail if the read operation fails. Without a sophisticated call analysis you can determine whether such exclusion applies if byte buffer gets passed directly to Copy but not if its gets passed through say a variable of Reader interface type.

 I recommend to use `_ =` to ignore the returned error. Maybe you can provide some examples to the contrary, but this doesn't feel like a sufficiently prevalent use case to add support for.

**Comment by simonbos** [comment]
Thanks for pointing that out @dtcaciuc , that's indeed the behavior. An example: https://go.dev/play/p/XX0Y3KmKFtg. I agree that ignoring it with `_ =` is ok.

Note that there are some examples of `io.Copy` in the README though:
https://github.com/kisielk/errcheck/blob/b832de3f3c5a608bbbd0e91fc7290d549267b05d/README.md?plain=1#L67-L68 Maybe it's worth adding a comment there (like for `(*net/http.Client).Do`).
