### ISSUE TITLE
Ignore all functions or functions matching a regex from a package 

### ISSUE THREAD

**Issue by pgimalac** [kisielk/errcheck#250]
Looking at the README, it seems `exclude` only supports listing functions explicitly, while the deprecated `ignore` supported regexes (and `ignorepkg` whole packages).

What is the alternative ?

It it on purpose considering excluding a whole package can easily ignore more than it should ? 
If so I think it should be explained in the README

Thank !

**Comment by dtcaciuc** [comment]
I believe the whole package ignore feature is intended to be used when entire package has not yet been (and until the time it's) sanitized and combed over error checking-wise. Individual excludes are really meant to precisely functions and interfaces like strings.Builder.Write that are documented to never fail, for example. 

On the other hand, regex or glob exclusions would be a footgun because depending how they're written and interpreted they can unintentionally capture other symbols (which can also be written after the rule is added).

**Comment by pgimalac** [comment]
Ok that's pretty much the answer I was expecting, thanks 👍
