### ISSUE TITLE
[feature] Detect panic

### ISSUE THREAD

**Issue by diegobernardes** [kisielk/errcheck#74]
Would be nice if this project could detect unhandled panic too or at least say where the code can panic.
So we could recover and the software dosen't crash.

**Comment by kisielk** [comment]
I don't think there's a general solution to this, since calls to panic() aren't the only way a goroutine could panic. You could for example dereference a nil pointer, divide by zero, have an index out of bounds error, or a number of other things. I don't think there's a general solution that would detect those possibilities.

**Comment by diegobernardes** [comment]
true, forgot this cases :/
