### ISSUE TITLE
Fails to build on Go 1.4

### ISSUE THREAD

**Issue by klauspost** [kisielk/errcheck#89]
We use errcheck for CI tests, for instance:
https://travis-ci.org/ncw/rclone/builds/100797264

Since you require Go 1.5, should we just use another tool, if we want to support 1.4 or lower?

**Comment by kisielk** [comment]
Would it help if I created a tag, and you could download the tag (instead of using go get) and build that?

**Comment by kostya-sh** [comment]
I think that there is no reason to run errcheck (or any other similar tools like vet or lint) that are compiled using different versions of Go during a build. Compiling errcheck using the latest Go version and running it once would only make the build faster.

It might be convenient though ;)

**Comment by kisielk** [comment]
Yeah, I also don't really see a reason why one would need to rebuild the lint tool on every build either.

**Comment by kostya-sh** [comment]
I blame travis for making it too easy to do ;)

**Comment by zimmski** [comment]
People removing errcheck from their workflow? This makes me sad.

@klauspost: I do not know of any alternative for errcheck. Also, if you are using go/types from the /x packages there is no way around migrating to a newer version because of https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY The package(s) will be removed from the upstream repository. You are forced to upgrade to a newer Go version. Our solution, at least for internal projects, is simple: vendor everything. We are then upgrading everything with a new Go version and from time to time we are also upgrading packages for bug and security fixes. This avoids the API-breaking changes at least for a while.

I agree that building the linting tools with the latest version of Go makes sense (and then cache it so there is no need to rebuild them -> if that is available in the CI) but that also implies that it is fine with everybody to handle and maintain a two-version-Go build. So that one can test a project with different Go versions. IMHO Go's lack of package versioning and the /x/ packages make the maintaining part especially depressing.

@kisielk: Was there ever an attempt to include errcheck into Go's `vet`?

**Comment by zimmski** [comment]
Oh, and I think we can simply close this issue. Unless we vendor the old go/types + dependencies and use them instead of the new go/types there is no way that errcheck supports something < 1.5 because of this statement: ` x/tools packages depending on 1.4 will be deleted 1 month after 1.6 has been released`

**Comment by kisielk** [comment]
I don't think errcheck is a good candidate for inclusion in vet because of too many false positives, and its usage is somewhat subjective. I'm pretty sure I discussed this a couple of years ago with the members of the go team.

**Comment by variadico** [comment]
+1

**Comment by zimmski** [comment]
@kisielk:
I think that the errcheck functionality would be an excellent addition for Go's vet:
- Not checking an error is a "suspicious construct", at least for me.
- Vet uses flags to activate certain checks so one can always keep the errcheck functionality disabled.
- The tool is OK with false-positives (btw. can you pinpoint me to one of errcheck? I never seen one in my code) I mean just look at the "shadowstrict" flag, and of course there is the description "... Vet uses heuristics that do not guarantee all reports are genuine problems... ".

Also, I really do not see a possible solution for this issue besides vendoring the old /x packages.

**Comment by klauspost** [comment]
>I don't think errcheck is a good candidate for inclusion in vet because of too many false positives, and its usage is somewhat subjective. 

Agree. It would be much more appropriate in [golint](https://github.com/golang/lint). go vet is for correctness, golint is for style. Ignoring errors is bad style, not inherently incorrect.

**Comment by dominikh** [comment]
> btw. can you pinpoint me to one of errcheck? I never seen one in my code

Any time an error is returned just to satisfy an interface, even if an error can never occur. You'll likely not check the error if working with the type directly.

> Vet uses flags to activate certain checks so one can always keep the errcheck functionality disabled

If the errcheck functionality was disabled by default, it wouldn't experience enough exposure. And if it's enabled by default, false positives are really not okay. The barrier to entrance is really high there.

Also I'm pretty sure that we've had this discussion before and the decision was not to integrate it with vet. Can someone find a reference to that?

**Comment by kisielk** [comment]
Yeah, I can't find the discussion right now but I definitely remember it happening.

**Comment by zimmski** [comment]
Would it make sense to propose including errcheck as an official tool in the STD or in /x/tools? My guess is that the functionality will not change besides adding stricter rules which can be turned on using command line arguments, and the project is then protected from API breaking changes.

**Comment by zimmski** [comment]
> > btw. can you pinpoint me to one of errcheck? I never seen one in my 
>
> Any time an error is returned just to satisfy an interface, even if an error can never occur. You'll likely not check the error if working with the type directly

I guess you are talking about something like `bytes.Buffer`? However, I strongly argue that this is a false-positive. If an interface defines that there can be an error it should be checked since that is one of the reasons to use interfaces: "Handle the interface not the implementation." The implementation can change any time and then an unhandled error of an interrface can silently become a problem if you do not check it in the first place.

**Comment by kisielk** [comment]
It's already in gometalinter and a few other similar tools. I don't really see how putting the project in to another would lessen the maintenance burden? Anyone is free to submit patches here.

There's basically no way the tool would get in to the standard distribution, the core Go team has already said they want to reduce the number of changes there. I don't really see the advantage of putting it in x/tools either. If anything, the Gerritt process used there would deter more contributors. Also I still think errcheck is too "fuzzy" to be one of the mainstream Go-team sanctioned tools. It definitely doesn't fit the model of vet, and I question if it fits with lint either.

I think having it called from something like gometalinter, an editor plugin, or as part of a build process is a better way to use it.

As far as stability, I think we should just track the last-released Go version. That's generally what x/tools does as well.

**Comment by dominikh** [comment]
> If an interface defines that there can be an error it should be checked since that is one of the reasons to use interfaces

Assuming the following code: 

```
var x bytes.Buffer
x.Write(nil)
```

I am *not* using the io.Writer interface, I am using the contract that the bytes.Buffer type establishes. And that contract explicitly states that "err is always nil". Ergo no future code changes, if they respect their own contract, can introduce an error return.

> and the project is then protected from API breaking changes

It would, however, not be protected from failing to work with older versions of Go, which is the topic of this issue. And as far as maintenance goes, I think this project is doing well. I agree with Kamil that moving it into /x/tools would increase the overhead, not decrease it. Also note that not even golint is in /x/tools.

This feels a lot like someone coming up with an idea first and then searching for arguments for it. There's really no net benefit to be had from being in the stdlib (which will never happen) or being in /x/tools.

**Comment by kisielk** [comment]
Going to close this. I don't have any intention of maintaining support of old Go versions myself. I'd gladly merge PRs that do so in an unobtrusive matter though.
