### ISSUE TITLE
`go get -u github.com/kisielk/errcheck` fails with `use of internal package not allowed`

### ISSUE THREAD

**Issue by veqryn** [kisielk/errcheck#97]
Go get fails, on Windows 7 (both normal cmd and mingw), and also in Linux:
```
$ go get -u github.com/kisielk/errcheck
package github.com/kisielk/errcheck
        imports github.com/kisielk/errcheck/internal/errcheck: use of internal package not allowed
```

**Comment by shurcooL** [comment]
What does `go version` print on the machines where it fails?

I can't reproduce (using Go 1.6):

![image](https://cloud.githubusercontent.com/assets/1924134/14003781/7ed72b48-f112-11e5-943d-937e427badd8.png)

**Comment by veqryn** [comment]
On windows:
```
$ go version
go version go1.6 windows/amd64
```

On linux: `go version go1.6 linux/amd64`

**Comment by veqryn** [comment]
I have also tried deleting the src and the pkg and bin directories, and trying again, but same results.

**Comment by shurcooL** [comment]
What does `go env` print?

Given you have Go 1.6 and you tried clearing `src` and `pkg` directories, I can only suspect you may have some bad environment variable or a bad installation of Go. Otherwise, it should work... I can't think of other reasons why it wouldn't.

Also, do you you use symlinks inside or around your GOPATH workspace?

**Comment by kisielk** [comment]
Yeah, it works for me with a clean GOPATH, so it's definitely an environment problem on your end.

**Comment by kisielk** [comment]
I'm going to close this issue since it's not a problem with the package. You'll probably have better luck sorting out your problem on a mailing list like golang-nuts anyway.
